### ISSUE TITLE
Does the follower API expose the npm user names of authors or contributors?

### ISSUE THREAD

**Issue by kemitchell** [npm/registry-follower-tutorial#2]
Not exactly sure if this belongs here. Please let me know if I ought to take it elsewhere!

The question: Does the current registry follower API include the npm user names of authors and contributors? I see the RFC-style name-address-URL info, but not npm user names.

**Comment by ashleygwilliams** [comment]
hey! not the npm usernames of the contributors. the only available data is the `_npmUser` which is the publishing user

**Comment by ashleygwilliams** [comment]
@kemitchell - gonna close, please reply/reopen if you still have questions! also i am watching this repo now so i shouldn't take friggin months to reply. sorry about that.
